import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { THEME_INIT_SCRIPT, THEME_STORAGE_KEY } from './theme';

// These only check the script source generated by this plain module — they
// exercise plain Node/Vitest imports, which never pass through the RSC
// client-reference substitution, so they CANNOT detect the layout.tsx ->
// themeStore import-boundary bug described below. See the "root layout
// import boundary" suite for the test that actually guards that.
describe('THEME_INIT_SCRIPT source (module-local content, not the RSC boundary)', () => {
  it('embeds the real storage key in the generated script', () => {
    expect(THEME_STORAGE_KEY).toBe('starter.theme');
    expect(THEME_INIT_SCRIPT).toContain("localStorage.getItem('starter.theme')");
  });

  it('contains no server-stub error text and stays syntactically valid', () => {
    expect(THEME_INIT_SCRIPT).not.toContain('Attempted to call');
    expect(THEME_INIT_SCRIPT).not.toContain('throw Error');
    // Throws if the script source is not parseable.
    expect(() => new Function(THEME_INIT_SCRIPT)).not.toThrow();
  });
});

describe('root layout import boundary', () => {
  it('does not import the theme constants from the client store', () => {
    // layout.tsx is a SERVER component. `themeStore` is a 'use client' module:
    // in a real RSC build, its exports become unusable client-reference stubs
    // when read from server code, which previously corrupted the before-paint
    // theme script into a SyntaxError and silently killed the anti-flash
    // feature. Vitest can't reproduce that stub substitution (it's an RSC-only
    // mechanism), so the only way to guard against regressing it is to assert
    // the import boundary at the source level.
    const layout = readFileSync(join(process.cwd(), 'src/app/layout.tsx'), 'utf8');

    expect(layout).not.toMatch(/from ['"]@\/store\/themeStore['"]/);
    expect(layout).toMatch(/from ['"]@\/lib\/theme['"]/);
  });
});
