'use client';

// EXAMPLE ONLY — fake and fully local (see public/demo-embed.js). Delete this whole folder
// when starting a real project; it's here to prove the embed tooling and lint rules work.

import { useEffect, useState } from 'react';
import { loadEmbedScript, resolveEmbedUrl } from '@/shared/lib/embeds';
import manifest from './embed.json';

/**
 * Generated by `pnpm embed:add demo-embed`. Fill in real URLs and props in embed.json,
 * or delete this folder entirely if you don't need it.
 */
export function DemoEmbed() {
  const [ready, setReady] = useState(false);

  useEffect(() => {
    let cancelled = false;
    const src = resolveEmbedUrl(manifest.urls, process.env.NODE_ENV);

    void loadEmbedScript({ src, tagName: manifest.tagName }).then(() => {
      if (!cancelled) {
        setReady(true);
      }
    });

    return () => {
      cancelled = true;
    };
  }, []);

  if (!ready) {
    return null;
  }

  return <demo-embed />;
}
