#!/usr/bin/env node
// Scaffolds src/shared/embeds/<name>/ from a template: index.ts, a wrapper component,
// a .d.ts for the custom element's JSX typing, and an embed.json manifest.
//
// Usage: pnpm embed:add <name>   (name must be kebab-case with at least one hyphen —
// custom element tag names are required to contain a hyphen per the Custom Elements spec)

import { appendFileSync, existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { CURRENT_EMBED_TEMPLATE_VERSION } from './embed-constants.mjs';

const projectRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const name = process.argv[2];

const NAME_PATTERN = /^[a-z][a-z0-9]*(-[a-z0-9]+)+$/;

function toPascalCase(kebab) {
  return kebab
    .split('-')
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join('');
}

function fail(message) {
  console.error(`❌ ${message}`);
  process.exit(1);
}

if (!name) {
  fail('Usage: pnpm embed:add <name> (kebab-case, must contain a hyphen, e.g. "demo-embed")');
}

if (!NAME_PATTERN.test(name)) {
  fail(`"${name}" must be lowercase kebab-case with at least one hyphen, e.g. "demo-embed".`);
}

const dir = join(projectRoot, 'src', 'shared', 'embeds', name);

if (existsSync(dir)) {
  fail(`src/shared/embeds/${name} already exists.`);
}

const pascalName = toPascalCase(name);

mkdirSync(dir, { recursive: true });

writeFileSync(join(dir, 'index.ts'), `export { ${pascalName} } from './${pascalName}';\n`);

writeFileSync(
  join(dir, `${pascalName}.tsx`),
  `'use client';

import { useEffect, useState } from 'react';
import { loadEmbedScript, resolveEmbedUrl } from '@/shared/lib/embeds';
import manifest from './embed.json';

/**
 * Generated by \`pnpm embed:add ${name}\`. Fill in real URLs and props in embed.json,
 * or delete this folder entirely if you don't need it.
 */
export function ${pascalName}() {
  const [ready, setReady] = useState(false);

  useEffect(() => {
    let cancelled = false;
    const src = resolveEmbedUrl(manifest.urls, process.env.NODE_ENV);

    void loadEmbedScript({ src, tagName: manifest.tagName }).then(() => {
      if (!cancelled) {
        setReady(true);
      }
    });

    return () => {
      cancelled = true;
    };
  }, []);

  if (!ready) {
    return null;
  }

  return <${name} />;
}
`,
);

writeFileSync(
  join(dir, `${name}.d.ts`),
  `import type { DetailedHTMLProps, HTMLAttributes } from 'react';

// JSX typing for the <${name}> custom element. React 19 moved the JSX namespace out of
// global scope and into the "react" module's own exports (re-exported from react/jsx-runtime),
// so with this project's "jsx": "react-jsx" tsconfig setting, augmenting \`declare module 'react'\`
// is what actually merges — a \`declare global { namespace JSX {...} }\` block does not.
declare module 'react' {
  namespace JSX {
    interface IntrinsicElements {
      '${name}': DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement>;
    }
  }
}

export {};
`,
);

writeFileSync(
  join(dir, 'embed.json'),
  JSON.stringify(
    {
      tagName: name,
      urls: {
        development: `/${name}.js`,
        staging: `/${name}.js`,
        production: `/${name}.js`,
      },
      allowedProps: [],
      forbiddenProps: [],
      templateVersion: CURRENT_EMBED_TEMPLATE_VERSION,
    },
    null,
    2,
  ) + '\n',
);

// steiger's fsd/public-api rule requires the shared/embeds segment itself to have a public
// API, on top of each embed's own index.ts — keep that segment-level barrel in sync here.
const segmentIndexPath = join(projectRoot, 'src', 'shared', 'embeds', 'index.ts');
const exportLine = `export { ${pascalName} } from './${name}';\n`;

if (existsSync(segmentIndexPath)) {
  appendFileSync(segmentIndexPath, exportLine);
} else {
  writeFileSync(
    segmentIndexPath,
    "// Public API for the shared/embeds segment, required by steiger's fsd/public-api rule.\n" +
      '// Add/remove one export line per folder generated by `pnpm embed:add` / deleted by hand.\n' +
      exportLine,
  );
}

console.log(`✓ src/shared/embeds/${name} scaffolded (tag: <${name}>)`);
console.log(`  Next: create public/${name}.js (or point urls.* at a real external script).`);
