// Public API for the shared/embeds segment, required by steiger's fsd/public-api rule.
// Add/remove one export line per folder generated by `pnpm embed:add` / deleted by hand.
export { DemoEmbed } from './demo-embed';
